# Generated by Django 6.0.3 on 2026-03-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_minutes',
            field=models.IntegerField(default=5, help_text='Minutes before deadline to remind'),
        ),
    ]
