# Generated by Django 6.0.3 on 2026-03-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline', '0002_task_reminder_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reminder_minutes',
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_time',
            field=models.TimeField(blank=True, help_text='Time of day to trigger reminder', null=True),
        ),
    ]
